name: 'Setup Node.js and Dependencies'
description: 'Setup Node.js with caching and install dependencies (requires prior checkout)'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  cache-key-suffix:
    description: 'Optional suffix for cache key (useful for matrix builds)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-${{ hashFiles('package-lock.json') }}${{ inputs.cache-key-suffix }}
        restore-keys: |
          ${{ runner.os }}-node-${{ inputs.node-version }}-
          ${{ runner.os }}-node-

    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci --prefer-offline --no-audit

    - name: Verify installation
      if: steps.cache-node-modules.outputs.cache-hit == 'true'
      shell: bash
      run: |
        echo "✅ Using cached node_modules"
        echo "Cache key: ${{ steps.cache-node-modules.outputs.cache-key }}"
