[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"

# Include scripts and migrations directories in the production image
[staticAssets]
"scripts" = "scripts"
"migrations" = "migrations"
