/**
 * Validation Schemas
 *
 * Zod validation schemas derived from Drizzle table definitions.
 * These schemas are used for runtime validation of insert/update operations.
 *
 * TODO: Split this file into domain-based validation files matching the table structure.
 * For now, we re-export from the original schema to maintain backward compatibility during migration.
 */

// NOTE: These will be refactored into domain-based files (validation/core.ts, validation/metrics.ts, etc.)
// in a future migration. For now, import from the original location to avoid breaking existing code.

export {
  insertOrganizationSchema,
  updateOrganizationStatusSchema,
  updateOrganizationSchema,
  deleteOrganizationSchema,
  insertTeamSchema,
  insertUserSchema,
  insertOAuthUserSchema,
  insertAthleteProfileSchema,
  insertUserOrganizationSchema,
  insertUserTeamSchema,
  insertInvitationSchema,
  insertMeasurementSchema,
  insertSiteMetricSchema,
  updateSiteMetricSchema,
  insertOrganizationMetricSchema,
  updateOrganizationMetricSchema,
  insertSiteSportSchema,
  updateSiteSportSchema,
  insertSitePositionSchema,
  updateSitePositionSchema,
  insertSiteBenchmarkSchema,
  updateSiteBenchmarkSchema,
  tierDefinitionSchema,
  insertTierGroupSchema,
  insertCustomBenchmarkSchema,
  updateCustomBenchmarkSchema,
  insertOrganizationBenchmarkSchema,
  updateOrganizationBenchmarkSchema,
  insertReportSchema,
  updateReportSchema,
  updateReportInsightsSchema,
  insertReportSnapshotSchema,
  insertReportBenchmarkSchema,
  insertAthleteSchema,
  insertSiteSettingsSchema,
  updateSiteSettingsSchema,
  insertGoalSchema,
  updateGoalSchema,
  insertMembershipRequestSchema,
  createMembershipRequestSchema,
  updateOrgMembershipSettingsSchema,
  insertPushSubscriptionSchema,
  updateNotificationPreferencesSchema,
  updateOrgNotificationSettingsSchema,
  insertEventSchema,
  updateEventSchema,
  insertEventRegistrationSchema,
  updateEventRegistrationSchema,
  insertEventInvitationSchema,
  insertEventMetricSchema,
  updateProfileSchema,
  changePasswordSchema,
  archiveTeamSchema,
  updateTeamMembershipSchema,
  createSiteAdminSchema,
  insertBenchmarkSetSchema,
  updateBenchmarkSetSchema,
  insertBenchmarkSetItemSchema,
  updateBenchmarkSetItemSchema,
  reorderBenchmarkSetItemsSchema,
} from "../schema-original";

// Insert type exports
export type {
  InsertOrganization,
  UpdateOrganization,
  UpdateOrganizationStatus,
  DeleteOrganization,
  InsertTeam,
  InsertUser,
  InsertOAuthUser,
  UpdateProfile,
  ChangePassword,
  ArchiveTeam,
  UpdateTeamMembership,
  InsertAthleteProfile,
  CreateSiteAdmin,
  InsertUserOrganization,
  InsertUserTeam,
  InsertInvitation,
  InsertAuditLog,
  InsertEmailVerificationToken,
  InsertMeasurement,
  InsertSiteMetric,
  UpdateSiteMetric,
  InsertOrganizationMetric,
  UpdateOrganizationMetric,
  InsertSiteSport,
  UpdateSiteSport,
  InsertSitePosition,
  UpdateSitePosition,
  TierDefinition,
  InsertTierGroup,
  InsertSiteBenchmark,
  UpdateSiteBenchmark,
  InsertCustomBenchmark,
  UpdateCustomBenchmark,
  InsertOrganizationBenchmark,
  UpdateOrganizationBenchmark,
  InsertReport,
  UpdateReport,
  InsertReportSnapshot,
  InsertReportBenchmark,
  InsertAthlete,
  InsertGoal,
  UpdateGoal,
  InsertMembershipRequest,
  CreateMembershipRequest,
  UpdateOrgMembershipSettings,
  InsertPushSubscription,
  UpdateNotificationPreferences,
  UpdateOrgNotificationSettings,
  InsertEvent,
  UpdateEvent,
  InsertEventRegistration,
  UpdateEventRegistration,
  InsertEventInvitation,
  InsertEventMetric,
  InsertBenchmarkSet,
  UpdateBenchmarkSet,
  InsertBenchmarkSetItem,
  UpdateBenchmarkSetItem,
  ReorderBenchmarkSetItems,
} from "../schema-original";
