name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
      actions: read

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Automated PR Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          prompt: |
            You are performing an automated code review for PR #${{ github.event.pull_request.number }}.

            Read the agent definition at .claude/agents/pr-lifecycle-agent.md for review guidelines.

            Tasks:
            1. Fetch PR diff: `gh pr diff ${{ github.event.pull_request.number }}`
            2. Read all changed files for context
            3. Perform comprehensive code review covering:
               - Code quality & best practices
               - Security vulnerabilities (OWASP Top 10)
               - Performance considerations
               - Test coverage
               - TypeScript type safety
               - AthleteMetrics conventions (from CLAUDE.md)
            4. Invoke specialized agents for domain-specific review if needed
            5. Post review comment using the format from pr-lifecycle-agent.md

            Use `gh pr comment ${{ github.event.pull_request.number }} --body "..."` to post your review.

            Important:
            - Follow AthleteMetrics patterns from CLAUDE.md
            - Use TodoWrite to track review tasks
            - Be constructive and specific in feedback

          claude_args: --max-turns 15 --allowed-tools "Bash(gh:*),Read,Grep,Glob,Task,TodoWrite"

          additional_permissions: |
            actions: read
            pull-requests: write

